# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('long_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длинный заголовок')),
                ('about', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Описание')),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.TreeItem', verbose_name='Родительский элемент')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
