# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treeitem',
            options={'verbose_name': 'Элемент курса', 'verbose_name_plural': 'Элементы курса'},
        ),
        migrations.AddField(
            model_name='treeitem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
