# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180507_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeItemFlat',
            fields=[
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'Список курсов',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.treeitem',),
        ),
        migrations.AlterModelOptions(
            name='treeitem',
            options={'verbose_name': 'элемент', 'verbose_name_plural': 'структура курсов'},
        ),
        migrations.AlterField(
            model_name='treeitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
