# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180527_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeitem',
            name='leaf',
            field=models.BooleanField(default=False, verbose_name='задача'),
        ),
    ]
