# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180617_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeitem',
            name='show',
            field=models.BooleanField(default=False, verbose_name='отображать'),
        ),
    ]
