# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('courses', '0007_auto_20180624_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeitem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='treeitem',
            name='source_raw_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор в источнике'),
        ),
        migrations.AlterField(
            model_name='treeitem',
            name='leaf',
            field=models.BooleanField(default=True, verbose_name='задача'),
        ),
    ]
