# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180704_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treeitem',
            options={'ordering': ['lft'], 'verbose_name': 'элемент структуры курсов', 'verbose_name_plural': 'структура курсов'},
        ),
        migrations.RemoveField(
            model_name='treeitem',
            name='leaf',
        ),
        migrations.AddField(
            model_name='treeitem',
            name='in_number_list',
            field=models.BooleanField(default=True, verbose_name='участвует в нумерации кура'),
        ),
        migrations.AddField(
            model_name='treeitem',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Задача'), ('2', 'Тема'), ('3', 'Курс')], default='1', max_length=1, null=True, verbose_name='тип'),
        ),
    ]
