# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.modules.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название группы', max_length=64, verbose_name='Название')),
                ('status', models.TextField(blank=True, help_text='Введите статус группы', verbose_name='Статус')),
                ('changed_status', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', project.modules.fields.JSONField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Открытая'), (1, 'Закрытая'), (2, 'Кодовое слово')], default=1, verbose_name='Статус')),
                ('codeword', models.CharField(blank=True, help_text='Введите кодовое слово', max_length=64, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='ModuleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Доступен'), (1, 'Скрыт'), (2, 'Таймер')], default=0, verbose_name='Статус')),
                ('open_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Открыть')),
                ('close_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Закрыть')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='groups.Group', verbose_name='Группа')),
            ],
        ),
    ]
