# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0002_auto_20180603_1017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название группы', max_length=64, verbose_name='Название')),
                ('status', models.TextField(blank=True, help_text='Введите статус группы', verbose_name='Статус')),
                ('changed_status', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.IntegerField(choices=[(0, 'Открытая'), (1, 'Закрытая'), (2, 'Кодовое слово')], default=1, verbose_name='Статус')),
                ('codeword', models.CharField(blank=True, help_text='Введите кодовое слово', max_length=64, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('members', models.ManyToManyField(blank=True, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Доступен'), (1, 'Скрыт'), (2, 'Таймер')], default=0, verbose_name='Статус')),
                ('open_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Открыть')),
                ('close_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Закрыть')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_module', to='groups.Group', verbose_name='Группа')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Модуль')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(blank=True, through='groups.GroupModule', to='modules.Module', verbose_name='Модули'),
        ),
        migrations.AddField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(related_name='ownership', to=settings.AUTH_USER_MODEL, verbose_name='Владельцы'),
        ),
    ]
