# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20180603_1017'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Доступен'), (1, 'Скрыт'), (2, 'Таймер')], default=0, verbose_name='Статус')),
                ('open_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Открыть')),
                ('close_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Закрыть')),
            ],
        ),
        migrations.RemoveField(
            model_name='moduledata',
            name='group',
        ),
        migrations.RemoveField(
            model_name='moduledata',
            name='module',
        ),
        migrations.AlterField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(blank=True, through='groups.GroupModule', to='modules.Module', verbose_name='Модули'),
        ),
        migrations.DeleteModel(
            name='ModuleData',
        ),
        migrations.AddField(
            model_name='groupmodule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_module', to='groups.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='groupmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Модуль'),
        ),
    ]
