# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(to='modules.Module', verbose_name='Модули'),
        ),
        migrations.AddField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(related_name='ownership', to=settings.AUTH_USER_MODEL, verbose_name='Владельцы'),
        ),
    ]
