# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledata',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(blank=True, through='groups.ModuleData', to='modules.Module', verbose_name='Модули'),
        ),
        migrations.AddField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(related_name='ownership', to=settings.AUTH_USER_MODEL, verbose_name='Владельцы'),
        ),
    ]
