# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190905_1255'),
        ('groups', '0002_auto_20180624_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.TreeItem', verbose_name='курс')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='groups.Group')),
            ],
        ),
    ]
