# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180314_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(blank=True, to='modules.Module', verbose_name='Модули'),
        ),
    ]
