# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180314_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='codeword',
            field=models.CharField(blank=True, help_text='Введите кодовое слово', max_length=64, verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='group',
            name='state',
            field=models.IntegerField(choices=[(0, 'Закрытая'), (1, 'Открытая'), (2, 'Кодовое слово')], default=0, verbose_name='Статус'),
        ),
    ]
