# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-03 14:38
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('key', models.CharField(choices=[('top', 'в шапке'), ('sidebar', 'в сайдбаре')], max_length=255, unique=True, verbose_name='тип меню')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', app.common.fields.OrderField(blank=True, null=True, verbose_name='порядок')),
                ('name', models.CharField(max_length=255, verbose_name='текст')),
                ('url', models.CharField(max_length=255, verbose_name='ссылка')),
                ('image', app.common.fields.AnyExtFileBrowseField(blank=True, max_length=1000, null=True, verbose_name='изображение')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='service.Menu')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
                'ordering': ('order_key',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Site')),
                ('confirm_signup', models.BooleanField(default=False, verbose_name='требуется подтверждение учетной записи после регистрации')),
                ('logo_title', models.TextField(blank=True, default='', null=True, verbose_name='текст логотипа')),
                ('logo_desc', models.TextField(blank=True, default='', null=True, verbose_name='описание логотипа')),
                ('copyright', models.TextField(blank=True, default='', help_text='формат: "© <текст копирайта ГГГГ> - текущий год", заполнять только часть в скобках', null=True, verbose_name='копирайт')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
            bases=('sites.site',),
        ),
    ]
