# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-10 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='confirm_signup',
            field=models.BooleanField(default=False, verbose_name='требуется подтверждение учетной записи после регистрации'),
        ),
    ]
