# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-13 11:29
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_sitesettings_confirm_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=1000, null=True, verbose_name='изображение'),
        ),
    ]
