# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-04 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20240525_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='signin',
            field=models.CharField(choices=[('all', 'Всем'), ('teacher', 'Только преподавателям'), ('superuser', 'Только суперпользователям')], default='all', max_length=255, verbose_name='Авторизация разрешена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup',
            field=models.BooleanField(default=True, help_text='Регистрация новых пользователей открыта', verbose_name='регистрация'),
        ),
    ]
