from app.tasks.api.views.task import TaskViewSet
from app.tasks.api.views.taskitem.main import TaskItemViewSet
from app.tasks.api.views.taskitem.php import PhpViewSet
from app.tasks.api.views.taskitem.csharp import CSharpViewSet
from app.tasks.api.views.taskitem.gcc74 import GCC74ViewSet
from app.tasks.api.views.taskitem.java import JavaViewSet
from app.tasks.api.views.taskitem.pascal import PascalViewSet
from app.tasks.api.views.taskitem.postgresql import PostgresqlViewSet
from app.tasks.api.views.taskitem.prologd import PrologDViewSet
from app.tasks.api.views.taskitem.python38 import Python38ViewSet
