# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название модуля', max_length=64, verbose_name='Название')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий к модулю', verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('tasks', models.ManyToManyField(blank=True, to='cms.Task')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
    ]
