# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.cms.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0004_auto_20180220_1902'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название модуля', max_length=64, verbose_name='Название')),
                ('units', project.cms.fields.JSONField(blank=True, null=True)),
                ('courses', models.ManyToManyField(to='cms.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
    ]
