# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(blank=True, to='cms.Course'),
        ),
    ]
