# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20180603_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='comment',
            field=models.TextField(blank=True, help_text='Введите комментарий к модулю', max_length=1024, null=True, verbose_name='Комментарий'),
        ),
    ]
