# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180220_1902'),
        ('modules', '0002_auto_20180314_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='module',
            name='units',
        ),
        migrations.AddField(
            model_name='module',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='cms.Task'),
        ),
    ]
