# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20180624_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'oлимпиада', 'verbose_name_plural': 'oлимпиады'},
        ),
        migrations.AlterField(
            model_name='module',
            name='comment',
            field=models.TextField(blank=True, help_text='Введите комментарий', max_length=1024, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='module',
            name='treeitems',
            field=models.ManyToManyField(blank=True, to='courses.TreeItem', verbose_name='задачи'),
        ),
    ]
