# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-03 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('last_changes', models.DateTimeField(auto_now_add=True, verbose_name='дата изменения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('file', filebrowser.fields.FileBrowseField(help_text='Файл данных PostgreSQL версии не ниже 13', max_length=1000, unique=True, verbose_name='файл')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'пользовательская база данных',
                'verbose_name_plural': 'пользовательские базы данных',
            },
        ),
    ]
