# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-15 11:05
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='file',
            field=models.FileField(
                help_text='Файл данных PostgreSQL версии не ниже 13',
                upload_to='uploads',
                verbose_name='файл'
            ),
        ),
    ]
