# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-15 11:05
from __future__ import unicode_literals

import app.databases.utils
import django.core.files.storage
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='file',
            field=models.FileField(
                help_text='Файл данных PostgreSQL версии не ниже 13',
                storage=django.core.files.storage.FileSystemStorage(
                    location=settings.SQL_FILES_DIR
                ), upload_to=app.databases.utils.get_db_file_path,
                verbose_name='файл'
            ),
        ),
    ]
