# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-13 11:29
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20220615_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='file',
            field=filebrowser.fields.FileBrowseField(
                blank=True,
                help_text='Файл данных PostgreSQL версии не ниже 13',
                max_length=1000,
                null=True,
                verbose_name='файл'
            ),
        ),
    ]
