# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('langs', '0003_auto_20200216_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('about', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='краткое описание')),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текстовый контент')),
                ('order_key', src.utils.fields.OrderField(blank=True, null=True, verbose_name='порядок')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs.Lang', verbose_name='язык программирования')),
            ],
            options={
                'verbose_name': 'Самостоятельная работа',
                'verbose_name_plural': 'самостоятельные работы',
                'ordering': ['order_key'],
            },
        ),
    ]
