# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 12:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import src.utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200330_1225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_status', models.CharField(choices=[('0', 'нет'), ('1', 'ожидает проверки'), ('2', 'в процессе проверки'), ('3', 'проверено')], default='0', max_length=255, verbose_name='статус проверки преподавателем')),
                ('tests_score', models.FloatField(blank=True, null=True, verbose_name='оценка по автотестам')),
                ('manual_score', models.FloatField(blank=True, null=True, verbose_name='оценка преподавателя')),
                ('last_changes', models.TextField(blank=True, default='', verbose_name='последние изменения')),
                ('version_best', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='лучшее решение')),
                ('version_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='список сохраненных решений')),
                ('comment', tinymce.models.HTMLField(blank=True, null=True, verbose_name='комментарий к решению')),
            ],
            options={
                'verbose_name': 'решение задачи',
                'verbose_name_plural': 'решения задач',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('max_score', models.PositiveIntegerField(default=5, verbose_name='балл за решение')),
                ('manual_check', models.BooleanField(default=False, verbose_name='ручная проверка')),
                ('compiler_check', models.BooleanField(default=True, verbose_name='проверка автотестами')),
                ('slug', src.utils.fields.SlugField(blank=True, max_length=255, null=True, verbose_name='слаг')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('order_key', src.utils.fields.OrderField(blank=True, null=True, verbose_name='порядок')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_taskitems', to='quizzes.Quiz', verbose_name='самостоятельная работа')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='tasks.Task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['order_key'],
            },
        ),
        migrations.AddField(
            model_name='solution',
            name='taskitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_solution', to='quizzes.TaskItem', verbose_name='задача'),
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
