# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20200403_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='number',
        ),
    ]
