# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langs', '0004_auto_20200511_1756'),
        ('quizzes', '0003_remove_taskitem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='langs',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='langs.Lang', verbose_name='язык программирования'),
        ),
    ]
