# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_taskitem_langs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='langs',
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата/время окончения решения задач в формате UTC'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения'),
        ),
    ]
