# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20200511_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='langg',
            field=models.CharField(blank=True, choices=[('python', 'Python3'), ('cpp', 'C++'), ('csharp', 'C#')], max_length=255, null=True, verbose_name='язык'),
        ),
    ]
