# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-17 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0006_taskitem_langg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='version_best',
        ),
        migrations.AddField(
            model_name='solution',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='листинг решения'),
        ),
        migrations.AddField(
            model_name='solution',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата/время отправки'),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_count',
            field=models.BooleanField(default=True, verbose_name='баллы идут в зачет'),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='запрещено изменять'),
        ),
        migrations.AddField(
            model_name='solution',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='заполняется автоматически, когда преподаватель выставляет оценку', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_solutions_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='taskitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='quizzes.TaskItem', verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_solution_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
