# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20200517_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер'),
        ),
    ]
