# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 13:32
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текст задания'),
        ),
    ]
