# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200330_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='код рещения')),
            ],
            options={
                'verbose_name': 'эталонное решение',
                'verbose_name_plural': 'эталонные решения',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'метка',
                'verbose_name_plural': 'метки',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('name',), 'verbose_name': 'источник', 'verbose_name_plural': 'источники'},
        ),
        migrations.RemoveField(
            model_name='source',
            name='content',
        ),
        migrations.RemoveField(
            model_name='source',
            name='order_key',
        ),
        migrations.RemoveField(
            model_name='source',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='source_raw_id',
        ),
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('0', 'очень простой'), ('1', 'простой'), ('2', 'средний'), ('3', 'сложный'), ('4', 'легендарный')], max_length=255, null=True, verbose_name='сложность'),
        ),
        migrations.AddField(
            model_name='solutionexample',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_examples', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='tasks.Tag', verbose_name='метки'),
        ),
    ]
