# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200411_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='output_type',
            field=models.CharField(choices=[('str', 'строка'), ('int', 'целое число'), ('float', 'вещественное число')], default='str', max_length=255, verbose_name='чекер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.Tag', verbose_name='метки'),
        ),
    ]
