# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200717_1025'),
    ]

    operations = [
    ]
