# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201107_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionexample',
            name='translator',
            field=models.IntegerField(choices=[(1, 'Python 3.8'), (2, 'GCC 7.5')], default=1, verbose_name='транслятор кода'),
            preserve_default=False,
        ),
    ]
