# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_solutionexample_translator'),
        ('training', '0016_auto_20220322_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionexample',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='текст решения'),
        ),
        migrations.AlterField(
            model_name='solutionexample',
            name='translator',
            field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д')], max_length=100, verbose_name='транслятор кода'),
        ),
        migrations.RunSQL(sql="""
            UPDATE tasks_solutionexample 
            SET translator = CASE
              WHEN translator = '1' THEN 'Python3.8'
              WHEN translator = '2' THEN 'GCC7.4'
            END
        """),
    ]
