# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-22 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_auto_20220322_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('translator', models.CharField(choices=[('Python3.8', 'Python3.8'), ('GCC7.4', 'GCC7.4'), ('Prolog-D', 'Prolog-D')], max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ]
        ),
        migrations.RunSQL("""
            INSERT INTO tasks_draft (
                task_id,
                user_id,
                translator,
                content
            ) SELECT
                tti.task_id,
                s.user_id,
                s.translator,
                s.last_changes
              FROM
                training_solution s
                INNER JOIN training_taskitem tti ON s.taskitem_id = tti.id
            ;
        """)
    ]
