# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20220514_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='translator',
            field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')], max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='translator',
            field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')], max_length=100, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='solutionexample',
            name='translator',
            field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')], max_length=100, verbose_name='транслятор кода'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_type',
            field=models.CharField(choices=[('str', 'строка'), ('int', 'целое число'), ('float', 'вещественное число'), ('select', 'SQL SELECT'), ('delete', 'SQL DELETE'), ('insert', 'SQL INSERT'), ('update', 'SQL UPDATE')], default='str', max_length=255, verbose_name='чекер'),
        ),
    ]
