# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20230616_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='рассчитывается автоматически', verbose_name='рейтинг'),
        ),
    ]
