# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-20 11:44
from __future__ import unicode_literals

import app.common.fields
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20220629_0021'),
        ('databases', '0002_auto_20220615_1105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_auto_20230619_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('type', models.CharField(choices=[('course', 'Курс'), ('taskbook', 'Задачник'), ('external', 'Внешний источник')], max_length=100, verbose_name='источник задачи')),
                ('max_score', models.PositiveIntegerField(default=5, verbose_name='балл за решение')),
                ('score_method', models.CharField(choices=[('tests', 'Тестирование кода'), ('review', 'Проверка преподавателем'), ('tests_and_review', 'Тестирование и проверка')], default='tests', max_length=50, verbose_name='метод оценивания')),
                ('slug', app.common.fields.TaskItemSlugField(blank=True, max_length=255, null=True, verbose_name='слаг')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('order_key', app.common.fields.OrderField(blank=True, null=True, verbose_name='порядок')),
                ('translator', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')], max_length=100), size=None, verbose_name='транслятор кода')),
                ('database', models.ForeignKey(blank=True, help_text='обязательна для задач по базам данных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='databases.Database', verbose_name='учебная база данных')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='UserPlagStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('type', models.CharField(choices=[('course', 'Курс'), ('taskbook', 'Задачник'), ('external', 'Внешний источник')], max_length=100, verbose_name='источник решения')),
                ('type_id', models.PositiveIntegerField(null=True, verbose_name='идентификатор источника решения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_hash', models.CharField(max_length=128)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('type', models.CharField(choices=[('course', 'Курс'), ('taskbook', 'Задачник'), ('external', 'Внешний источник')], max_length=100, verbose_name='источник решения')),
                ('type_id', models.PositiveIntegerField(null=True, verbose_name='идентификатор источника решения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='type',
            field=models.CharField(choices=[('course', 'Курс'), ('taskbook', 'Задачник'), ('external', 'Внешний источник')], max_length=100, verbose_name='источник решения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('0', 'Очень простая'), ('1', 'Простая'), ('2', 'Средняя'), ('3', 'Сложная'), ('4', 'Легендарная')], max_length=255, null=True, verbose_name='сложность'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskitems', to='tasks.Task', verbose_name='задача'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskitems', to='training.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='userstatistics',
            unique_together=set([('user', 'type', 'type_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='userplagstatistics',
            unique_together=set([('user', 'type', 'type_id')]),
        ),
    ]
