# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-22 15:46
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20230620_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='number',
        ),
        migrations.AddField(
            model_name='solution',
            name='score',
            field=models.FloatField(help_text='рассчитывается автоматически', null=True, verbose_name='итоговая оценка'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='order_key',
            field=app.common.fields.OrderField(blank=True, null=True, verbose_name='порядковый номер'),
        ),
    ]
