# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-22 18:43
#
# Migrate
#   training Taskitem -> tasks Taskitem
# Calculate solution score

from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20230622_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='translator',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')],
                    max_length=10000
                ),
                size=None,
                verbose_name='транслятор кода'
            ),
        ),
        migrations.RunSQL("""
        INSERT INTO tasks_taskitem (
          show,
          type,
          topic_id,
          task_id,
          max_score,
          score_method,
          slug,
          order_key,
          translator,
          database_id
        )
        SELECT
          tt.show,
          'course',
          tt.topic_id,
          tt.task_id,
          tt.max_score,
          tt.score_method,
          tt.slug,
          tt.order_key,
          ARRAY[tc.translator],
          ttop.database_id
        FROM training_taskitem tt 
          INNER JOIN training_topic ttop
            ON tt.topic_id = ttop.id
          INNER JOIN training_course tc
            ON ttop.course_id = tc.id
        """),
        migrations.RunSQL("""
            WITH solution AS (
               SELECT
                 id, 
                 (
                     CASE
                       WHEN score_method = 'tests' THEN testing_score
                       WHEN review_status = 'checked' THEN review_score
                       ELSE NULL
                     END
                 ) score
               FROM tasks_solution
            )
            UPDATE tasks_solution
              SET score = solution.score
            FROM solution
            WHERE tasks_solution.id = solution.id
        """)
    ]
