# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-22 15:46
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models


def update_tests(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    db_alias = schema_editor.connection.alias
    for task in Task.objects.using(db_alias).only('tests').all():
        for test in task.tests:
            test['show'] = True
        task.save(update_fields=['tests'])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20230622_1843'),
    ]

    operations = [
        migrations.RunPython(
            code=update_tests,
            reverse_code=migrations.RunPython.noop
        )
    ]
