# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-22 15:46
from __future__ import unicode_literals

from django.db import migrations


def update_tests(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    db_alias = schema_editor.connection.alias
    for task in Task.objects.using(db_alias).all():
        tests = task.tests
        for test in tests:
            test['data_in'] = test['input']
            test['data_out'] = test['output']
            test['visible'] = True
            test['enabled'] = True
            if test.get('show') is not None:
                del test['show']
            if test.get('input') is not None:
                del test['input']
            if test.get('output') is not None:
                del test['output']
        task.tests = tests
        task.save(update_fields=['tests'])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20230622_1843'),
    ]

    operations = [
        migrations.RunPython(
            code=update_tests,
            reverse_code=migrations.RunPython.noop
        )
    ]
