# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-03 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_migrate_task_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('content', models.TextField(verbose_name='содержимое')),
            ],
            options={
                'verbose_name': 'чекер',
                'verbose_name_plural': 'чекеры',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='testing_checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Checker', verbose_name='Функция сверки решения с тестами'),
        ),
    ]
