# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_migrate_checkers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='output_type',
        ),
        migrations.AlterField(
            model_name='checker',
            name='content',
            field=models.TextField(help_text='def checker(right_value: str, value: str) -> bool:', verbose_name='Функция сверки решения'),
        ),
    ]
