# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 12:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191117_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='output_type',
            field=models.CharField(choices=[('str', 'строка'), ('int', 'целое число'), ('float', 'вещественное число')], default='str', max_length=255, verbose_name='тип решения для автотестов'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tests',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='автотесты'),
        ),
    ]
