# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200717_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionexample',
            name='lang',
            field=models.CharField(blank=True, choices=[('python', 'Python3'), ('cpp', 'C++'), ('csharp', 'C#'), ('java', 'Java')], max_length=255, null=True, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lang',
            field=models.CharField(blank=True, choices=[('python', 'Python3'), ('cpp', 'C++'), ('csharp', 'C#'), ('java', 'Java')], max_length=255, null=True, verbose_name='язык'),
        ),
    ]
