# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-11 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200610_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionexample',
            name='lang',
            field=models.CharField(blank=True, choices=[('python', 'Python3'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('sql', 'sql')], max_length=255, null=True, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lang',
            field=models.CharField(blank=True, choices=[('python', 'Python3'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('sql', 'sql')], max_length=255, null=True, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_type',
            field=models.CharField(choices=[('str', 'строка'), ('int', 'целое число'), ('float', 'вещественное число'), ('sqlselect', 'sql select запрос')], default='str', max_length=255, verbose_name='тип решения для автотестов'),
        ),
    ]
