# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('long_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длинный заголовок')),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('long_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длинный заголовок')),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('long_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длинный заголовок')),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
