# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('long_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длинный заголовок')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('long_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длинный заголовок')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('long_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длинный заголовок')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
