# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
