# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 16:53
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое'),
        ),
    ]
