# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-09 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('python', 'Python 3.6'), ('cpp', 'C++'), ('csharp', 'C#')], max_length=255, unique=True, verbose_name='заголовок')),
            ],
            options={
                'verbose_name': 'язык программирования',
                'verbose_name_plural': 'языки программирования',
            },
        ),
    ]
