# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер'),
        ),
        migrations.AddField(
            model_name='topic',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер'),
        ),
    ]
