# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20191122_1910'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='solution',
            name='status',
        ),
        migrations.AddField(
            model_name='solution',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='комментарий к решению'),
        ),
        migrations.AddField(
            model_name='solution',
            name='manual_score',
            field=models.FloatField(blank=True, null=True, verbose_name='оценка преподавателя'),
        ),
        migrations.AddField(
            model_name='solution',
            name='manual_status',
            field=models.CharField(choices=[('0', 'нет'), ('1', 'ожидает проверки'), ('2', 'в процессе проверки'), ('3', 'проверено')], default='0', max_length=255, verbose_name='статус проверки преподавателем'),
        ),
        migrations.AddField(
            model_name='solution',
            name='tests_score',
            field=models.FloatField(blank=True, null=True, verbose_name='оценка по автотестам'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='compiler_check',
            field=models.BooleanField(default=True, verbose_name='проверка автотестами'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='manual_check',
            field=models.BooleanField(default=False, verbose_name='ручная проверка'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='max_score',
            field=models.PositiveIntegerField(default=5, verbose_name='балл за решение'),
        )
    ]
