# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0004_remove_taskitem_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='заполняется автоматически, когда преподаватель выставляет оценку', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_solutions', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='content',
            name='input',
            field=models.TextField(blank=True, null=True, verbose_name='Консольный ввод'),
        ),
        migrations.AlterField(
            model_name='content',
            name='show_input',
            field=models.BooleanField(default=False, verbose_name='Отображать консольный ввод'),
        ),
    ]
