# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20200420_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='version_best',
        ),
    ]
