# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_solution_version_best'),
        ('training', '0005_auto_20200403_1756'),
    ]

    operations = [
    ]
