# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-07 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_solution_version_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_solution', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
