# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'источник',
                'verbose_name_plural': 'источники',
            },
        ),
    ]
