# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-08 11:30
from __future__ import unicode_literals

import app.accounts.managers
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Ученик'), ('teacher', 'Преподаватель')], default='user', max_length=20, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким логином уже существует.'}, help_text='Обязательно. 150 не более символов. Буквы, цифры и знаки @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='логин'),
        ),
        migrations.RunSQL("""
            UPDATE auth_user SET role='teacher' 
            WHERE id in (
                select distinct(author_id) from groups_group
            )
        """)
    ]
