# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220408_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Ученик'), ('teacher', 'Преподаватель')], default='user', help_text='Преподаватели имеют доступ ко всем решениям', max_length=20, verbose_name='роль'),
        ),

    ]
