# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220422_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Ученик'), ('teacher', 'Преподаватель')], default='learner', help_text='Преподаватели имеют доступ ко всем решениям', max_length=20, verbose_name='роль'),
        ),
    ]
