# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-03 14:38
from __future__ import unicode_literals

import app.common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, null=True, verbose_name='Консольный ввод')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Редактор')),
                ('show_input', models.BooleanField(default=False, verbose_name='Отображать консольный ввод')),
                ('show_debug', models.BooleanField(default=True, verbose_name='Отображать отладчик')),
                ('readonly', models.BooleanField(default=False, verbose_name='Только для чтения')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ace', 'код'), ('text', 'текст')], default='text', max_length=255, verbose_name='тип')),
                ('order_key', app.common.fields.OrderField(blank=True, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'блок контента',
                'verbose_name_plural': 'блоки контента',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('translator', models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')], max_length=100, verbose_name='транслятор кода')),
                ('about', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='краткое описание')),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текстовый контент')),
                ('content_bottom', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текстовый контент под списком тем')),
                ('order_key', app.common.fields.OrderField(blank=True, null=True, verbose_name='порядок')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'учебный курс',
                'verbose_name_plural': 'учебные курсы',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, verbose_name='слаг')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи решения')),
                ('order_key', app.common.fields.OrderField(blank=True, null=True, verbose_name='порядок')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_topics', to='training.Course', verbose_name='курс')),
                ('database', models.ForeignKey(blank=True, help_text='обязательна для курсов по базам данных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='databases.Database', verbose_name='учебная база данных')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
                'ordering': ['order_key'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_content', to='training.Topic'),
        ),
    ]
