# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_solution_version_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='one_try',
            field=models.BooleanField(default=False, verbose_name='одна попытка'),
        ),
    ]
