# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_course_translator'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE training_course DROP COLUMN IF EXISTS lang_id')
    ]
