# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20220322_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='translator',
            field=models.CharField(choices=[('Python3.8', 'Python3.8'), ('GCC7.4', 'GCC7.4'), ('Prolog-D', 'Prolog-D')], max_length=100),
        ),
    ]
