# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-05 08:31
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0016_auto_20220322_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_hash', models.CharField(max_length=128)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courseuserstatistics',
            unique_together=set([('user', 'course')]),
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='end_time',
            new_name='due_date',
        ),
        migrations.AlterField(
            model_name='topic',
            name='due_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Дата сдачи решения'
            )
        )
    ]
