# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20220505_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='score_method',
            field=models.CharField(choices=[('tests', 'тестирование кода'), ('review', 'проверка преподавателем'), ('tests_and_review', 'тестирование и проверка')], default='tests', max_length=50, verbose_name='метод оценивания'),
        ),
        migrations.RunSQL("""
            UPDATE training_taskitem SET score_method = (
                CASE
                    WHEN manual_check IS TRUE AND compiler_check IS TRUE
                        THEN 'tests_and_review'
                    WHEN manual_check IS TRUE THEN 'review'
                    WHEN compiler_check IS TRUE THEN 'tests'
                END
            )
        """)
    ]
