# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20220420_1813'),
        ('training', '0018_auto_20220514_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='compiler_check',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='manual_check',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='one_try',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='score_method',
            field=models.CharField(choices=[('tests', 'Тестирование кода'), ('review', 'Проверка преподавателем'), ('tests_and_review', 'Тестирование и проверка')], default='tests', max_length=50, verbose_name='метод оценивания'),
        )
    ]
