# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-15 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_auto_20220514_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='translator',
            field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')], max_length=100, verbose_name='транслятор кода'),
        ),
    ]
