# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20220615_1105'),
        ('tasks', '0011_auto_20220514_1046'),
        ('databases', '0002_auto_20220615_1105'),
        ('accounts', '0003_auto_20220422_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='taskitem',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.AlterField(
            model_name='topic',
            name='database',
            field=models.ForeignKey(
                blank=True,
                help_text='обязательна для курсов по базам данных',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='databases.Database',
                verbose_name='учебная база данных'
            )
        )
    ]
