# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-13 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_auto_20220615_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='translator',
            field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('Pascal', 'PascalABC.NET')], max_length=100, verbose_name='транслятор кода'),
        ),
    ]
