# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-13 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20231113_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseuserstatistics',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='courseuserstatistics',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseuserstatistics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='course',
            name='translator',
        ),
        migrations.DeleteModel(
            name='CourseUserStatistics',
        ),
        migrations.DeleteModel(
            name='TaskItem',
        ),
    ]
