# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-29 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_auto_20230622_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
    ]
