# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-13 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_auto_20231113_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='due_date',
        ),
    ]
