# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-13 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_remove_topic_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='readonly',
        ),
        migrations.RemoveField(
            model_name='content',
            name='show_debug',
        ),
        migrations.RemoveField(
            model_name='content',
            name='show_input',
        ),
    ]
