# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-13 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_auto_20231113_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order_key'], 'verbose_name': 'раздел сайта', 'verbose_name_plural': 'разделы сайта'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_key'], 'verbose_name': 'страница', 'verbose_name_plural': 'страницы'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='number',
        ),
    ]
