# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('input', models.TextField(blank=True, null=True, verbose_name='входные данные')),
                ('output', models.TextField(blank=True, null=True, verbose_name='выходные данные')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='решение')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'код',
                'verbose_name_plural': 'код',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Python 3.6')], unique=True, verbose_name='название')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'исполнитель кода',
                'verbose_name_plural': 'исполнители кода',
            },
        ),
    ]
