# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Статичный'), (2, 'Исполняемый(компактный)'), (3, 'Исполняемый')], default=1, verbose_name='тип')),
                ('executor', models.IntegerField(blank=True, choices=[(1, 'Python 3.6')], help_text='если не выбран то наследуется', null=True, verbose_name='Исполнитель')),
                ('content', models.TextField(blank=True, null=True, verbose_name='код')),
                ('input', models.TextField(blank=True, null=True, verbose_name='ввод')),
                ('output', models.TextField(blank=True, null=True, verbose_name='вывод')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='решение')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'блок кода',
                'verbose_name_plural': 'блоки кода',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Python 3.6')], verbose_name='название')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'исполнитель кода',
                'verbose_name_plural': 'исполнители кода',
            },
        ),
    ]
