# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='name',
            field=models.IntegerField(choices=[(0, 'Python 3.6'), (1, 'Test 1'), (2, 'Test 2')], unique=True, verbose_name='Наименование'),
        ),
    ]
