# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'блок кода', 'verbose_name_plural': 'блоки кода'},
        ),
        migrations.AddField(
            model_name='code',
            name='type',
            field=models.IntegerField(choices=[(0, 'Статичный'), (1, 'Исполняемый')], default=0, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='code',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='содержимое'),
        ),
    ]
