# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(default='{"solutions": []}', verbose_name='детали решения')),
                ('success', models.BooleanField(default=False, verbose_name='задача решена')),
                ('execute_count', models.PositiveIntegerField(default=0, verbose_name='количество запусков кода')),
                ('check_tests_count', models.PositiveIntegerField(default=0, verbose_name='количество запусков тестирования')),
            ],
        ),
        migrations.CreateModel(
            name='CodeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, null=True, verbose_name='входные данные')),
                ('output', models.TextField(blank=True, null=True, verbose_name='правильный ответ')),
            ],
        ),
        migrations.RenameField(
            model_name='code',
            old_name='executor',
            new_name='executor_type_id',
        ),
        migrations.RemoveField(
            model_name='code',
            name='output',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='name',
        ),
        migrations.AddField(
            model_name='code',
            name='content_max_signs',
            field=models.PositiveIntegerField(default='1000', verbose_name='макс. символов в коде'),
        ),
        migrations.AddField(
            model_name='code',
            name='input_max_signs',
            field=models.PositiveIntegerField(default='100', verbose_name='макс. символов на входе'),
        ),
        migrations.AddField(
            model_name='code',
            name='save_solutions',
            field=models.BooleanField(default=False, verbose_name='сохранять пользовательские решения'),
        ),
        migrations.AddField(
            model_name='executor',
            name='type_id',
            field=models.IntegerField(choices=[(1, 'Python 3.6')], default=1, verbose_name='тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='type',
            field=models.IntegerField(choices=[(1, 'Статичный'), (2, 'Исполняемый'), (3, 'Исполняемый(с тестами)')], default=1, verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='codetest',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executors.Code', verbose_name='блок кода'),
        ),
        migrations.AddField(
            model_name='codesolution',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executors.Code', verbose_name='блок кода'),
        ),
        migrations.AddField(
            model_name='codesolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
