# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0002_auto_20180519_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesolution',
            options={'verbose_name': 'пользовательское решение', 'verbose_name_plural': 'пользовательские решения'},
        ),
        migrations.AlterModelOptions(
            name='codetest',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AddField(
            model_name='code',
            name='show_input',
            field=models.BooleanField(default=False, verbose_name='отображать блок ввода'),
        ),
        migrations.AddField(
            model_name='code',
            name='show_tests',
            field=models.BooleanField(default=False, verbose_name='отображать блок тестов'),
        ),
        migrations.AddField(
            model_name='code',
            name='timeout',
            field=models.PositiveIntegerField(default=30, verbose_name='макс. время исполнения(секунд)'),
        ),
        migrations.AlterField(
            model_name='code',
            name='content_max_signs',
            field=models.PositiveIntegerField(default=1000, verbose_name='макс. символов в блоке кода'),
        ),
        migrations.AlterField(
            model_name='code',
            name='input_max_signs',
            field=models.PositiveIntegerField(default=100, verbose_name='макс. символов в блоке ввода'),
        ),
        migrations.AlterField(
            model_name='code',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='эталонное решение'),
        ),
        migrations.AlterField(
            model_name='code',
            name='type',
            field=models.IntegerField(choices=[(1, 'Статичный'), (2, 'Исполняемый')], default=1, verbose_name='тип'),
        ),
    ]
