# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180527_1423'),
        ('executors', '0003_auto_20180525_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFlat',
            fields=[
            ],
            options={
                'verbose_name': 'блок кода',
                'verbose_name_plural': 'блоки кода',
                'proxy': True,
                'indexes': [],
            },
            bases=('executors.code',),
        ),
        migrations.RemoveField(
            model_name='code',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='code',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='object_id',
        ),
        migrations.AddField(
            model_name='code',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='code',
            name='treeitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.TreeItem', verbose_name='элемент курса'),
        ),
        migrations.AddField(
            model_name='executor',
            name='treeitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.TreeItem'),
            preserve_default=False,
        ),
    ]
