# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0003_auto_20180410_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='executor',
            field=models.IntegerField(blank=True, choices=[(1, 'Python 3.6')], help_text='если не выбран то наследуется', null=True, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='name',
            field=models.IntegerField(choices=[(1, 'Python 3.6')], unique=True, verbose_name='название'),
        ),
    ]
