# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0004_auto_20180410_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='name',
            field=models.IntegerField(choices=[(1, 'Python 3.6')], verbose_name='название'),
        ),
    ]
