# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0005_auto_20180602_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeflat',
            options={'verbose_name': 'элемент списка блоков кода', 'verbose_name_plural': 'список блоков кода'},
        ),
    ]
