# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0006_auto_20180617_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='executor_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Python 3.6')], default=1, help_text='если не выбран то наследуется', null=True, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='code',
            name='type',
            field=models.IntegerField(choices=[(1, 'Статичный'), (2, 'Исполняемый')], default=2, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'best_solution_num': False, 'best_solution_tests': [], 'solutions': []}, verbose_name='детали решения'),
        ),
    ]
