# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0007_auto_20180624_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='executor_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Python 3.6'), (2, 'C++'), (3, 'C#')], default=1, help_text='если не выбран то наследуется', null=True, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='type_id',
            field=models.IntegerField(choices=[(1, 'Python 3.6'), (2, 'C++'), (3, 'C#')], verbose_name='тип'),
        ),
    ]
