# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 13:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0008_auto_20190901_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersolution',
            options={'verbose_name': 'решение', 'verbose_name_plural': 'решения'},
        ),
        migrations.RemoveField(
            model_name='usersolution',
            name='progress',
        ),
        migrations.AddField(
            model_name='usersolution',
            name='best',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='лучшее решение'),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='last_changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='последние изменения'),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), default=list, size=None, verbose_name='сохраненные решения'),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='детали решения'),
        ),
    ]
