# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-16 03:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0009_auto_20190914_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersolution',
            name='versions',
        ),
        migrations.AddField(
            model_name='usersolution',
            name='versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='сохраненные решения'),
        ),
    ]
