# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='show_table',
            field=models.BooleanField(default=False, verbose_name='отображать таблицу результатов'),
        ),
    ]
