# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200507_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='show_table',
            field=models.BooleanField(default=False, verbose_name='отображать таблицу результатов'),
        ),
        migrations.AddField(
            model_name='groupquiz',
            name='show_table',
            field=models.BooleanField(default=False, verbose_name='отображать таблицу результатов'),
        ),
    ]
