# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-16 16:38
from __future__ import unicode_literals

import app.common.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0012_auto_20230616_1638'),
        ('databases', '0002_auto_20220615_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('max_score', models.PositiveIntegerField(default=5, verbose_name='балл за решение')),
                ('score_method', models.CharField(choices=[('tests', 'Тестирование кода'), ('review', 'Проверка преподавателем'), ('tests_and_review', 'Тестирование и проверка')], default='tests', max_length=50, verbose_name='метод оценивания')),
                ('slug', app.common.fields.TaskItemSlugField(blank=True, max_length=255, null=True, verbose_name='слаг')),
                ('translator', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Python3.8', 'Python 3.8'), ('GCC7.4', 'С++ (GCC 7.4)'), ('Prolog-D', 'Пролог-Д'), ('PostgreSQL', 'PostgreSQL 13'), ('Pascal', 'PascalABC.NET')], max_length=100), size=None, verbose_name='транслятор кода')),
                ('database', models.ForeignKey(blank=True, help_text='обязательна для задач по базам данных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='databases.Database', verbose_name='учебная база данных')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskbook_items', to='tasks.Task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['id'],
            },
        ),
    ]
