# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-03 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBookItem',
            fields=[
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.taskitem',),
        ),
    ]
