from app.translators.services.base import BaseTranslatorService
from app.translators.services.python38 import Python38Service
from app.translators.services.gcc74 import GCC74Service
from app.translators.services.prologd import PrologDService
from app.translators.services.postgresql import PostgresqlService
from app.translators.services.pascal import PascalService
from app.translators.services.php import PhpService
from app.translators.services.csharp import CsharpService
from app.translators.services.java import JavaService
