# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-16 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lang',
            name='provider',
        ),
        migrations.AddField(
            model_name='lang',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='lang',
            name='provider_name',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('cpp', 'cpp'), ('csharp', 'csharp')], max_length=255, null=True, verbose_name='провайдер'),
        ),
    ]
