- name: update code
  git:
    repo={{ git_repository }}
    dest={{ app_dir }}
    accept_hostkey=yes
    clone=yes
    version={{ git_branch }}
    force=yes
    update=yes
    refspec='+refs/heads/{{ git_branch }}:refs/remotes/origin/{{ git_branch }}'
    key_file=/ansible/.ssh/id_rsa_cappa_deployment_key
