# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-03 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('year', models.PositiveIntegerField(null=True, verbose_name='учебный год')),
                ('status', models.CharField(choices=[('0', 'открыто'), ('1', 'закрыто'), ('2', 'по кодовому слову')], default='1', max_length=255, verbose_name='вступление в группу')),
                ('codeword', models.CharField(blank=True, max_length=255, null=True, verbose_name='кодовое слово')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('show_date_last_seen', models.BooleanField(verbose_name='показывать колонку "Дата последнего входа"')),
                ('show_date_joined', models.BooleanField(verbose_name='показывать колонку "Дата регистрации"')),
                ('show_status', models.BooleanField(verbose_name='показывать колонку "Статус онлайн"')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
            },
        ),
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_access', models.CharField(choices=[('only_for_teachers', 'Для преподавателей'), ('allow_for_all', 'Для преподавателей и учеников'), ('closed', 'закрыт')], default='allow_for_all', help_text='отвечает за видимость таблицы с итогами курса', max_length=100, verbose_name='доступ к групповой статистике')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Course', verbose_name='курс')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='groups.Group')),
            ],
            options={
                'verbose_name': 'учебный курс',
                'verbose_name_plural': 'учебные курсы',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Преподаватель'), ('learner', 'Ученик')], default='learner', max_length=50, verbose_name='роль')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'ordering': ('-role', 'user__last_name', 'user__first_name', 'user__father_name'),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(related_name='training_groups', through='groups.GroupCourse', to='training.Course'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='training_groups', through='groups.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(help_text='Формальное указание владельца. Для работы с группой достаточно быть в статусе преподавателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupcourse',
            unique_together=set([('group', 'course')]),
        ),
    ]
