# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-29 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupcourse_show_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='show_date_joined',
            field=models.BooleanField(default=0, verbose_name='показывать колонку "Дата регистрации"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='show_date_last_seen',
            field=models.BooleanField(default=1, verbose_name='показывать колонку "Дата последнего входа"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='show_status',
            field=models.BooleanField(default=1, verbose_name='показывать колонку "Статус"'),
            preserve_default=False,
        ),
    ]
