# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-22 18:53
from __future__ import unicode_literals
import django
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210629_0907'),
        ('accounts', '0003_auto_20220422_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='_members',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='show',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.PositiveIntegerField(verbose_name='учебный год', null=True),
        ),
        migrations.RunSQL("""
            UPDATE groups_group SET year=date_part('year', CAST(creation_date AS DATE))
        """),
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('learner', 'Ученик')], default='learner', max_length=50, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(
                help_text=(
                    'Формальное указание владельца.'
                    ' Для работы с группой достаточно быть в статусе преподавателя'
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='владелец'
            ),
        ),
        migrations.RunSQL("""
            INSERT INTO groups_groupmember (user_id, group_id, role)
                SELECT gg.owner_id, gg.id, 'teacher'
                FROM groups_group gg
            ON CONFLICT (group_id, user_id) DO UPDATE SET role='teacher' 
        """)
    ]
