# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20220425_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={
                'ordering': (
                    'user__last_name',
                    'user__first_name',
                    'user__father_name'
                )
            }
        ),
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(related_name='training_groups', through='groups.GroupCourse', to='training.Course'),
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='statistics_access',
            field=models.CharField(
                choices=[
                    ('only_for_teachers', 'Для преподавателей'),
                    ('allow_for_all', 'Для преподавателей и учеников'),
                    ('closed', 'закрыт')
                ],
                default='allow_for_all',
                help_text='отвечает за видимость таблицы с итогами курса',
                max_length=100,
                verbose_name='доступ к групповой статистике'
            ),
        ),
        migrations.RunSQL("""
            UPDATE groups_groupcourse 
              SET statistics_access = (
                CASE
                  WHEN show_table IS TRUE THEN 'allow_for_all'
                  ELSE 'closed'
                END
              )
        """)
    ]
