# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20220507_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcourse',
            name='show_table',
        )
    ]
