# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-25 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20220507_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ('-role', 'user__last_name', 'user__first_name', 'user__father_name')},
        ),
    ]
