from app.tasks.services.solution import SolutionService
from app.tasks.services.taskitem.base import BaseTaskItemService
from app.tasks.services.taskitem.php import PhpService
from app.tasks.services.taskitem.pascal import PascalService
from app.tasks.services.taskitem.prologd import PrologDService
from app.tasks.services.taskitem.python38 import Python38Service
from app.tasks.services.taskitem.java import JavaService
from app.tasks.services.taskitem.postgrsql import PostgresqlService
from app.tasks.services.taskitem.gcc74 import GCC74Service
from app.tasks.services.taskitem.rust186 import Rust186Service
from app.tasks.services.taskitem.csharp import CsharpService
from app.tasks.services.taskitem.go123 import Go123Service
from app.tasks.services.taskitem.node20 import Node20Service
from app.tasks.services.taskitem.java17 import Java17Service
from app.tasks.services.taskitem.kotlin23 import Kotlin23Service
from app.tasks.services.taskitem.ruby4 import Ruby4Service
from app.tasks.services.taskitem.python314 import Python314Service
