from app.tasks.services.solution import SolutionService
from app.tasks.services.taskitem.base import BaseTaskItemService
from app.tasks.services.taskitem.php import PhpService
from app.tasks.services.taskitem.pascal import PascalService
from app.tasks.services.taskitem.prologd import PrologDService
from app.tasks.services.taskitem.python38 import Python38Service
from app.tasks.services.taskitem.java import JavaService
from app.tasks.services.taskitem.postgrsql import PostgresqlService
from app.tasks.services.taskitem.gcc74 import GCC74Service
